import opml from 'opml-generator'
import fs from 'fs'
import r from 'ramda'

const data = fs.readFileSync("resolved-data.cache.json", "utf8")

const header = {
  "title": "All feeds found in your twitter friends, generated by feedblogz",
  "dateCreated": new Date(),
  "ownerName": "Tobias Kloht"
}

function getFeedUrl(htmlUrl, xmlUrl) {
  if (xmlUrl.trim().substring(0,1) === "/") {
    return htmlUrl
      .trim()
      .replace(/\/$/, "")
      .concat(xmlUrl.trim())
  }
  return xmlUrl
}

const outlines = r.pipe(
  JSON.parse,
  r.filter(x => x.feedLinks&& x.feedLinks.length > 0),
  r.map(x => x.feedLinks.map(feedLink => {
    return({
       text: `${x.name} (@${x.screen_name})`,
       title: feedLink.title || x.description,
       type: "rss",
       "xmlUrl": getFeedUrl(x.url, feedLink.href),
       "htmlUrl": x.url
    })
  })),
  r.flatten
)(data)

const result = opml(header, outlines);// => XML

fs.writeFileSync("feedblogz.opml", result)

console.log('>>> ', result)